<?php ?>
<head>
    <title>NoFrills Layout</title>
</head>
<h1>Hello bitch</h1>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a justo et ipsum suscipit rutrum non et metus. Mauris et
    lorem vel ligula pulvinar venenatis eu facilisis velit. Aenean et nisl nec tellus facilisis accumsan. Nam sit amet
    convallis est. Nunc scelerisque justo justo, in feugiat quam eleifend at. Duis euismod tincidunt feugiat. Duis
    fringilla faucibus viverra. Maecenas tortor tellus, porta vel magna sit amet, rhoncus luctus nibh. Aenean rutrum
    justo ut commodo facilisis. Aliquam eleifend at ligula ut sodales. Curabitur tellus mauris, feugiat a finibus sit
    amet, sodales ut justo. Integer in ipsum dignissim, placerat ex eget, viverra urna. In gravida ac magna nec
    venenatis. Curabitur congue, augue sed ornare aliquam, urna elit vehicula velit, tristique tempor est elit id metus.
    Nunc ultrices orci non mauris sagittis euismod.
</p>

<p>
    <?php echo $this->getChildHtml('the_first'); ?>
</p>
<p>
    <?php echo $this->getChildHtml('the_second'); ?>
</p>
<!--<p>-->
<!--    --><?php //echo $this->getChildHtml(); ?>
<!--</p>-->
<!--<p>-->
<!--    The second paragraph is hard-coded in .phtml file-->
<!--</p>-->